### ISSUE TITLE
Raspberry Pi image creation instructions

### ISSUE THREAD

**Issue by kassah** [ChickenDevs/webcast#3]
Hi,
I'm going to be adding some centralized control features to this for myself, and it would be really nice if I had some instructions on how to build a new raspberry pi image to work with. Could you please add those instructions to you wiki?

**Comment by ChickenDevs** [comment]
I'll add a guide of how to build the raspberry pi from scratch soon. For just the base image you'll just need to follow the first few steps.

I'll reply here again when that wiki page is up, and tell you what steps to follow.

**Comment by ChickenDevs** [comment]
It should be good, You'll want steps 12-17 from [This Wiki Page](https://github.com/ChickenDevs/webcast/wiki/Image-Build-Instructions). We have thrown this together pretty quickly, so please let me know if this doesn't do what you wanted.

**Comment by kassah** [comment]
That looks great. I'll give it a try hopefully tonight or tomorrow night.

**Comment by kassah** [comment]
Definitely noticed two steps missing.
- [ ] missing a `sudo chmod a+x /etc/webcast/webcast.py` in setup.sh
- [ ] missing a `chown webcast:webcast /etc/webcast/webcast.*` in setup.sh

Still having issues getting the cockpit portal to display anything but "Failed" when I try to save a new config even after those changes.

**Comment by ChickenDevs** [comment]
There should be one more command, `chmod 664 /etc/webcast/webcast.conf` which will fix the "Failed" issue.
Updated setup.sh.

Thanks for the feedback!
